//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;

public class Flashing_Lights_Long:Flashing_Lights
{
	public override float timeFlashing {
		get {
			return 0.3F;
		} 
	}

}

